### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by KienB** [mrflashstudio/Quack#1]
When I did compiled and try this one and i get overflow

`byte[] buffer = ReadMemory(region.BaseAddress, region.RegionSize.ToUInt32());`

from this code 
QuaverProcess.cs 71 Line

`Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.UIntPtr.ToUInt32()
   at Quaver.API.Memory.Processes.QuaverProcess.FindPattern(String pattern, UIntPtr& result) in C:\Users\Kien\Desktop\Quack-master\Quaver.API\Memory\Processes\QuaverProcess.cs:line 71
   at Quaver.API.QuaverManager.Initialize() in C:\Users\Kien\Desktop\Quack-master\Quaver.API\QuaverManager.cs:line 68
   at Quack.Program.Main(String[] args) in C:\Users\Kien\Desktop\Quack-master\Quack\Program.cs:line 29`

**Comment by mrflashstudio** [comment]
Hopefully fixed by dad3c87 . Please let me know if you still experience this issue!
